# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/8"

  config.vm.network "forwarded_port", guest: 8801, host: 8801 # laravel_a
  config.vm.network "forwarded_port", guest: 8802, host: 8802 # laravel_b

  config.vm.synced_folder '.'            ,'/vagrant'              ,type: "rsync" # vagrant
  #config.vm.synced_folder '../laravel_a' ,'/workspaces/laravel_a' ,type: "rsync" # laravel_a
  #config.vm.synced_folder '../laravel_b' ,'/workspaces/laravel_b' ,type: "rsync" # laravel_b

  # virtualbox Only
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    #vb.memory = "2042"
    vb.name = "AlumaLinux 8(Laravel)"
    vb.cpus = 2
  end

  # provisions
  # japanese setting
  config.vm.provision :shell, :path => "scripts/japanese.sh"
  # AlmaLinux Update
  config.vm.provision :shell, :path => "scripts/osupdate.sh"
  # nginx
  config.vm.provision :shell, :path => "scripts/nginx.sh"
  # php
  config.vm.provision :shell, :path => "scripts/php.sh"
  # composer
  config.vm.provision :shell, :path => "scripts/composer.sh", privileged: false
  # laravel
  config.vm.provision :shell, :path => "scripts/laravel.sh", privileged: false
end
